# ──────────────────────────────────────────────────────────────────────────
# AnsCloud — Self-Hosted Setup Script (Cloudflare Tunnel)
#
# Jalankan di komputer yang akan jadi server AnsCloud.
# Script ini akan:
#   1. Cek/install Bun runtime
#   2. Clone repo AnsCloud (atau pakai kode di folder ini)
#   3. Setup .env dengan konfigurasi yang aman
#   4. Inisialisasi database
#   5. Build aplikasi Next.js
#   6. Mulai AnsCloud di port 3000 (PM2 untuk auto-restart)
#   7. Cek/install cloudflared (Cloudflare Tunnel client)
#
# Setelah script ini selesai, jalankan setup-tunnel.sh untuk konfigurasi domain.
# ──────────────────────────────────────────────────────────────────────────

#!/usr/bin/env bash
set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}   AnsCloud Self-Hosted Setup${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo ""

# Detect OS
OS="unknown"
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  OS="linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  OS="macos"
elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then
  OS="windows"
fi

if [[ "$OS" == "unknown" ]]; then
  echo -e "${RED}Error: OS tidak dikenali ($OSTYPE)${NC}"
  exit 1
fi

echo -e "${YELLOW}OS terdeteksi: $OS${NC}"
echo ""

# 1. Cek Bun
echo -e "${GREEN}[1/7] Cek Bun runtime...${NC}"
if command -v bun &>/dev/null; then
  echo -e "  ✓ Bun sudah terinstall: $(bun --version)"
else
  echo -e "  ✗ Bun belum terinstall. Installing..."
  if [[ "$OS" == "macos" ]]; then
    brew install oven-sh/bun/bun
  elif [[ "$OS" == "linux" ]]; then
    curl -fsSL https://bun.sh/install | bash
    export BUN_INSTALL="$HOME/.bun"
    export PATH="$BUN_INSTALL/bin:$PATH"
  else
    echo -e "${YELLOW}  Silakan install Bun manual: https://bun.sh/docs/installation${NC}"
    exit 1
  fi
  echo -e "  ✓ Bun terinstall: $(bun --version)"
fi
echo ""

# 2. Cek repo
echo -e "${GREEN}[2/7] Cek kode AnsCloud...${NC}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [[ -f "$SCRIPT_DIR/package.json" ]] && grep -q "anscloud" "$SCRIPT_DIR/package.json" 2>/dev/null; then
  cd "$SCRIPT_DIR"
  echo -e "  ✓ Menggunakan kode di folder: $SCRIPT_DIR"
else
  echo -e "  Kode AnsCloud tidak ditemukan di folder ini."
  read -p "  Clone dari GitHub? (URL repo atau kosongkan untuk skip): " REPO_URL
  if [[ -n "$REPO_URL" ]]; then
    git clone "$REPO_URL" "$SCRIPT_DIR/anscloud"
    cd "$SCRIPT_DIR/anscloud"
  else
    echo -e "${YELLOW}  Silakan jalankan script ini dari folder AnsCloud.${NC}"
    exit 1
  fi
fi
echo ""

# 3. Install dependencies
echo -e "${GREEN}[3/7] Install dependencies...${NC}"
bun install
echo -e "  ✓ Dependencies terinstall"
echo ""

# 4. Setup .env
echo -e "${GREEN}[4/7] Setup .env...${NC}"
if [[ -f ".env" ]]; then
  echo -e "  .env sudah ada. Backup ke .env.bak"
  cp .env .env.bak
fi

if [[ ! -f ".env" ]]; then
  # Generate random secrets
  NEXTAUTH_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p)
  
  cat > .env << EOF
# AnsCloud Environment Configuration
# Generated by setup.sh on $(date)

# Database (SQLite — stored in db/custom.db)
DATABASE_URL=file:$(pwd)/db/custom.db

# Login credentials — ISI dengan email & password hash kamu
# Untuk generate password hash:
#   bun -e "import bcrypt from 'bcryptjs'; console.log(bcrypt.hashSync('PASSWORD_KAMU', 12))"
# Lalu escape setiap \$ jadi \$ di hash (penting!)
ANSCLOUD_LOGIN_EMAIL=email@anangsetya.my.id
ANSCLOUD_LOGIN_PASSWORD_HASH="\$2b\$12\$REPLACE_WITH_YOUR_HASH"

# NextAuth — random secret (already generated for you)
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
# Update ke https://drive.anangsetya.my.id setelah tunnel jalan
NEXTAUTH_URL=http://localhost:3000

# Google OAuth (opsional — untuk Google Drive asli)
# GOOGLE_CLIENT_ID=xxxxx.apps.googleusercontent.com
# GOOGLE_CLIENT_SECRET=xxxxx
# ANSCLOUD_PUBLIC_URL=https://drive.anangsetya.my.id
EOF
  echo -e "  ✓ .env dibuat. EDIT dulu sebelum lanjut!"
  echo -e "${YELLOW}  ⚠️  Buka .env, isi password hash yang benar!${NC}"
  echo -e "${YELLOW}     Generate hash: bun -e \"import bcrypt from 'bcryptjs'; console.log(bcrypt.hashSync('PASSWORD_KAMU', 12))\"${NC}"
  echo -e "${YELLOW}     Lalu escape \$ jadi \$ di hash (e.g. \\\$2b\\\$12\\\$abc...)${NC}"
  echo ""
  read -p "  Tekan Enter setelah edit .env (atau Ctrl+C untuk batal)... "
fi
echo ""

# 5. Init database
echo -e "${GREEN}[5/7] Inisialisasi database...${NC}"
bun run db:push
echo -e "  ✓ Database siap"
echo ""

# 6. Build
echo -e "${GREEN}[6/7] Build aplikasi Next.js...${NC}"
echo -e "  Building (mungkin butuh 2-5 menit)..."
bun run build
echo -e "  ✓ Build selesai"
echo ""

# 7. Setup PM2 untuk auto-restart
echo -e "${GREEN}[7/7] Setup PM2 (auto-restart)...${NC}"
if ! command -v pm2 &>/dev/null; then
  echo -e "  Installing PM2..."
  if command -v npm &>/dev/null; then
    npm install -g pm2
  else
    bun add -g pm2
  fi
fi

pm2 delete anscloud 2>/dev/null || true
pm2 start "bun run start" --name anscloud
pm2 save

# Setup PM2 startup (auto-start saat komputer nyala)
echo -e "${YELLOW}  Untuk auto-start saat komputer nyala, jalankan:${NC}"
echo -e "  pm2 startup"
echo -e "  (PM2 akan kasih command untuk di-copy-paste, jalankan command itu)"
echo ""
echo -e "  Lalu simpan konfigurasi:"
echo -e "  pm2 save"
echo ""

# Cek status
sleep 2
echo -e "${GREEN}Status AnsCloud:${NC}"
pm2 status anscloud
echo ""

# Test
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✓ AnsCloud berhasil di-setup!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "Akses lokal: ${GREEN}http://localhost:3000${NC}"
echo ""
echo -e "${YELLOW}Langkah selanjutnya:${NC}"
echo -e "  1. Test di browser: http://localhost:3000"
echo -e "  2. Login dengan email & password yang sudah di-set di .env"
echo -e "  3. Setup Cloudflare Tunnel untuk akses via domain:"
echo -e "     ./setup-tunnel.sh"
echo ""
echo -e "${YELLOW}Command PM2 yang berguna:${NC}"
echo -e "  pm2 status          - lihat status"
echo -e "  pm2 logs anscloud   - lihat log real-time"
echo -e "  pm2 restart anscloud - restart app"
echo -e "  pm2 stop anscloud   - stop app"
echo ""
